### ISSUE TITLE
Issue running kminion with TLS enabled

### ISSUE THREAD

**Issue by mrandreyeff** [redpanda-data/kminion#157]
Hi there,
I'm trying to enable TLS, so I've added TLS files and configs:
```
      tls:
        enabled: true
        caFilepath: /opt/certs/kafka/ca.crt
        certFilepath: /opt/certs/kafka/tls.crt
        keyFilepath: /opt/certs/kafka/tls.key
```
After applied, I get error:
```
{"level":"warn","ts":"2022-07-22T12:40:40.460Z","logger":"main.kgo_client","msg":"unable to open connection to broker","addr":"kafka1:9093","broker":"seed 1","err":"tls: server sent two HelloRetryRequest messages"}
{"level":"warn","ts":"2022-07-22T12:40:40.465Z","logger":"main.kgo_client","msg":"unable to open connection to broker","addr":"kafka2:9093","broker":"seed 0","err":"tls: server sent two HelloRetryRequest messages"}
{"level":"fatal","ts":"2022-07-22T12:40:40.465Z","logger":"main.kgo_client","msg":"failed to test connectivity to Kafka cluster","error":"failed to request metadata: unable to dial: tls: server sent two HelloRetryRequest messages"}
```
There are multiple other clients using java and python, also tried the same TLS credentials with python (PEM format) - worked well. Kafka brokers use Java 11, so according to docs it shall be TLS 1.3.
As far as I see, after some googling shows the error shall come from https://github.com/golang/go/blob/master/src/crypto/tls/handshake_client_tls13.go#L296
Does anybody use TLS 1.3 with kminion?
Are there any configs that may help from broker/client side?
