### ISSUE TITLE
Error on message lag on consumer offsets

### ISSUE THREAD

**Issue by HighWatersDev** [redpanda-data/kminion#167]
Hi,

I'm running kminion v2.2.0 and it started off just fine. However, after time, I'm getting these errors:

```text
{"level":"info","ts":"2022-09-19T16:08:11.957Z","logger":"main.storage","msg":"Tried to fetch consumer group offsets, but haven't consumed the whole topic yet"}
{"level":"info","ts":"2022-09-19T16:08:12.031Z","logger":"main.minion_service","msg":"catching up the message lag on consumer offsets","lagging_partitions_count":1,"lagging_partitions":[{"Name":"__consumer_offsets","Id":6,"Lag":328}],"total_lag":328}
```

values.yaml

```yaml
deployment:
  volumes:
    secrets:
      - secretName: kafka-tls
        mountPath: /secret/tls
kminion:
  config:
    kafka:
      brokers:
        - kafka-cluster-sc-kafka-0.kafka-cluster-sc-kafka-brokers.kafka.svc.cluster.local:9094
        - kafka-cluster-sc-kafka-1.kafka-cluster-sc-kafka-brokers.kafka.svc.cluster.local:9094
        - kafka-cluster-sc-kafka-2.kafka-cluster-sc-kafka-brokers.kafka.svc.cluster.local:9094
      clientId: "kminion"
      tls:
        enabled: true
        caFilepath: "/secret/tls/ca.crt"
        certFilepath: "/secret/tls/tls.crt"
        keyFilepath: "/secret/tls/tls.key"
    minion:
      consumerGroups:
        enabled: true
        scrapeMode: offsetsTopic # Valid values: adminApi, offsetsTopic
        granularity: partition
        allowedGroups: [ ".*" ]
        ignoredGroups: [ ]
      topics:
        granularity: partition
        allowedTopics: [ ".*" ]
        ignoredTopics: [ ]
        infoMetric:
          configKeys: [ "cleanup.policy" ]
      logDirs:
        enabled: true

      endToEnd:
        enabled: true
        probeInterval: 100ms
        topicManagement:
          enabled: true
          name: kminion-end-to-end
          reconciliationInterval: 10m
          replicationFactor: 1
          partitionsPerBroker: 1

        producer:
          ackSla: 5s
          requiredAcks: all

        consumer:
          groupIdPrefix: kminion-end-to-end
          deleteStaleConsumerGroups: false
          roundtripSla: 20s
          commitSla: 10s
serviceMonitor:
  create: true
  additionalLabels:
    release: prom-stack
```
